version: 0.0.{build}

image: Visual Studio 2019

test: off

environment:
  NUGET_API_KEY:
    secure: ojJHQQHSQs/rgIRopbuHUQcjWpVgwaXhjYpW2kdkjS6NZta2A3Zzaz9k2yf+XooV

install:
  - cmd: git submodule update --init
  - cmd: dotnet tool install --global GitVersion.Tool

build_script:
  - cmd: .\build.cmd --appveyor

artifacts:
  - path: YamlDotNet\bin\Release\netstandard2.1
    name: Release-NetStandard-2.1

  - path: YamlDotNet\bin\Release\netstandard1.3
    name: Release-NetStandard-1.3

  - path: YamlDotNet\bin\Release\net45
    name: Release-Net45

  - path: YamlDotNet\bin\Release\net35
    name: Release-Net35

  - path: YamlDotNet\bin\Release\net20
    name: Release-Net20

  - path: YamlDotNet\bin\Release\net40
    name: Release-UnitySubset-v35

  - path: YamlDotNet\bin\*.nupkg
